### PR TITLE
Moving a subgroup does not force a recreation of the group and no longer deletes the underlying projects

### LINKED ISSUE #574: Moving subgroup deletes underlying projects
### Terraform Version
```
Terraform v0.14.6
+ provider registry.terraform.io/gitlabhq/gitlab v3.4.0
```

### Affected Resource(s)
- gitlab_group
- gitlab_project

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "gitlab_group" "ansible_roles" {
  name                    = "ansible-roles"
  path                    = "ansible-roles"
  description             = "Ansible roles"
  parent_id               = gitlab_group.ace.id        # <---- this is what I updated
  subgroup_creation_level = "owner"
  project_creation_level  = "maintainer"
  request_access_enabled  = true
}

resource "gitlab_project" "ansible_roles" {
  for_each = local.ansible_roles

  name                                             = each.key
  description                                      = each.value
  default_branch                                   = "master"
  namespace_id                                     = gitlab_group.ansible_roles.id
  visibility_level                                 = "internal"
  initialize_with_readme                           = true
  approvals_before_merge                           = 0
  only_allow_merge_if_pipeline_succeeds            = false
  only_allow_merge_if_all_discussions_are_resolved = false
  remove_source_branch_after_merge                 = true
  container_registry_enabled                       = false
  issues_enabled                                   = true
  merge_requests_enabled                           = true
  packages_enabled                                 = true
  pipelines_enabled                                = true
  shared_runners_enabled                           = false
  snippets_enabled                                 = true
  wiki_enabled                                     = false

  lifecycle {
    # guard against accidental destruction of this repository
    prevent_destroy = true
  }
}
```

### Plan output

```
Terraform will perform the following actions:

  # gitlab_group.ansible_roles must be replaced
-/+ resource "gitlab_group" "ansible_roles" {
      ~ full_name                         = "old_path / ansible-roles" -> (known after apply)
      ~ full_path                         = "old_path/ansible-roles" -> (known after apply)
      ~ id                                = "3589" -> (known after apply)
        name                              = "ansible-roles"
      ~ parent_id                         = 2147 -> 6994 # forces replacement
      ~ runners_token                     = (sensitive value)
      ~ visibility_level                  = "internal" -> (known after apply)
      ~ web_url                           = "https://..{redacted}...ansible-roles" -> (known after apply)
        # (12 unchanged attributes hidden)
    }

  # gitlab_project.ansible_roles["base"] will be updated in-place
  ~ resource "gitlab_project" "ansible_roles" {
        id                                               = "4088"
        name                                             = "base"
      ~ namespace_id                                     = 3589 -> (known after apply)
        tags                                             = []
        # (29 unchanged attributes hidden)
    }
.... 
# repeat for other ansible role projects
```

### Expected Behavior

- Subgroup would relocated its new parent group
- Projects would follow

or at the very least there would be an error indicating that Terraform couldn't destroy my projects given `prevent=destroy`.

### Actual Behavior

- Subgroup was destroyed and recreated under new parent group (normal)
- All projects appear to have been deleted

### Apply Output

```
gitlab_group.ansible_roles: Destroying... [id=3589]
gitlab_group.ansible_roles: Still destroying... [id=3589, 10s elapsed]
gitlab_group.ansible_roles: Still destroying... [id=3589, 20s elapsed]
gitlab_group.ansible_roles: Destruction complete after 26s
gitlab_group.ansible_roles: Creating...
gitlab_group.ansible_roles: Creation complete after 1s [id=7048]
gitlab_project.ansible_roles["base"]: Modifying... [id=4088]
gitlab_project.ansible_roles["vault"]: Modifying... [id=4359]
....
# repeat for remaining ansible role projects

Error: PUT https://..{redacted}../api/v4/projects/4359/transfer: 404 {message: 404 Project Not Found}

  on projects.tf line 126, in resource "gitlab_project" "ansible_roles":
 126: resource "gitlab_project" "ansible_roles" {

Error: PUT https://..{redacted}../api/v4/projects/4088/transfer: 404 {message: 404 Project Not Found}

  on projects.tf line 126, in resource "gitlab_project" "ansible_roles":
 126: resource "gitlab_project" "ansible_roles" {

...
# repeat for remaining ansible role projects
```

### Steps to Reproduce

- Change subgroup parent id
- `terraform apply`

### Important Factoids

Pretty severe given:

1. moving a group (destroy/recreate) deletes all projects despite no indication from plan that this is what will happen
2. destructive action bypasses lifecycle destruction prevention

### PR DESCRIPTION
**Pull request by gro-gg**
## Description

fixes #574 

### PR Checklist Acknowledgement

- [x] I acknowledge that all of the following items are true, where applicable:
  - Resource attributes match 1:1 the names and structure of the API resource in [the GitLab API documentation](https://docs.gitlab.com/ee/api/).
  - [Examples](https://github.com/gitlabhq/terraform-provider-gitlab/tree/main/examples) are updated with:
    - A \*.tf file for the resource/s with at least one usage example
    - A \*.sh file for the resource/s with an import example (if applicable)
  - New resources have at minimum a basic test with three steps:
    - Create the resource
    - Update the attributes
    - Import the resource
  - No new `//lintignore` comments were copied from existing code. (Linter rules are meant to be enforced on new code.)

### Tests

To test that the nested group is not recreated, I misused the AutoDevopsEnabled attribute. It ensures that the value is still true after transferring the nested group. If the group was recreated, it would be false again (default value). Please let me know if you have a better idea how to test this.

### CODE REVIEW

File: internal/provider/resource_gitlab_group.go [hunk 1]
```diff
@@ -369,9 +368,40 @@ func resourceGitlabGroupUpdate(ctx context.Context, d *schema.ResourceData, meta
...
+
+	opt := &gitlab.TransferSubGroupOptions{}
+	if parentId != 0 {
+		log.Printf("[DEBUG] transfer gitlab group %s from %v to new parent group %v", d.Id(), o, n)
+		opt.GroupID = gitlab.Int(parentId)
+	} else {
+		log.Printf("[DEBUG] turn gitlab group %s from %v to a new top-level group", d.Id(), o)
+	}
+
+	_, _, err := client.Groups.TransferSubGroup(d.Id(), opt)
```
Comment (timofurrer) [inline internal/provider/resource_gitlab_group.go:397]: Let's use the context here from the CRUD function (has to be passed to the `transferSubGroup` function):

```suggestion
	_, _, err := client.Groups.TransferSubGroup(d.Id(), opt, gitlab.WithContext(ctx))
```

File: internal/provider/resource_gitlab_group.go [hunk 2]
```diff
@@ -369,9 +368,40 @@ func resourceGitlabGroupUpdate(ctx context.Context, d *schema.ResourceData, meta
...
+		diagnostic := transferSubGroup(d, client)
+		if diagnostic.HasError() {
+			return diagnostic
+		}
+	}
+
 	return resourceGitlabGroupRead(ctx, d, meta)
 }
 
+func transferSubGroup(d *schema.ResourceData, meta interface{}) diag.Diagnostics {
```
Comment (timofurrer) [inline internal/provider/resource_gitlab_group.go:381]: (non-blocking): I think it would make sense to already pass the GitLab client and attributes needed directly to this function. Also, return an `error` instead of `Diagnostics` - we don't use the warning feature anyways.

WDYT?

File: internal/provider/resource_gitlab_group_test.go [hunk 3]
```diff
@@ -199,27 +201,26 @@ func TestAccGitlabGroup_nested(t *testing.T) {
...
-			//			ProjectCreationLevel:  "maintainer", // default value
-			//			SubGroupCreationLevel: "owner",      // default value
-			//			TwoFactorGracePeriod:  48,           // default value
-			//			DefaultBranchProtection: 2,          // default value
-			// 			Parent:      &group,
-			// 		}),
-			// 	),
-			// },
+			{
+				Config: testAccGitlabNestedGroupConfig(rInt),
```
Comment (timofurrer) [inline internal/provider/resource_gitlab_group_test.go:205]: A few ideas to make this test step more transparent:

* doesn't the group id stay the same after the transfer? We may be able to check for this instead of the non-intuitive `auto_devops_enabled` attribute check
* another idea could actually be to verify what you wanted to achieve (or at least what the PR title states): testing if underlying projects are preserved during a group transfer. Since these are acceptance tests I think it's okay to even introduce a separate test case to test that particular behavior.

WDYT?

**Review by timofurrer — CHANGES_REQUESTED** [review]
Thanks @gro-gg for the change! 

I've left a few comments. 

Back to you 🏓

File: internal/provider/resource_gitlab_group.go (hunk 1 above)
Comment (gro-gg) [reply internal/provider/resource_gitlab_group.go:397]: completely agree, I forgot

File: internal/provider/resource_gitlab_group.go (hunk 2 above)
Comment (gro-gg) [reply internal/provider/resource_gitlab_group.go]: no emotions, I will fix it...

File: internal/provider/resource_gitlab_group_test.go (hunk 3 above)
Comment (gro-gg) [reply internal/provider/resource_gitlab_group_test.go:205]: Checking the group id was my first idea. But this means that I have to keep a state between the test steps. This seemed a bit ugly to me. I will try this approach again though. :+1:

Comment (timofurrer) [reply internal/provider/resource_gitlab_group_test.go:205]: I don't think it's necessarily a bad idea. Here is an example where it's already done: 
https://github.com/gitlabhq/terraform-provider-gitlab/blob/145117ca03d4f91a5fd2fec325c8a0c60106913e/internal/provider/resource_gitlab_project_issue_test.go#L92

Comment (gro-gg) [reply internal/provider/resource_gitlab_group_test.go:205]: I have also tried the idea with the projects. But I don't think that works with the setup of the test steps. If the project is created in the Config with Terraform, then it is also created again after a re-create of the group. So I need to test if the project was recreated or not. So I am facing the same problem as with the groups. :man_juggling:

Comment (timofurrer) [reply internal/provider/resource_gitlab_group_test.go:205]: You can create test projects outside of the terraform config, e.g.:

https://github.com/gitlabhq/terraform-provider-gitlab/blob/145117ca03d4f91a5fd2fec325c8a0c60106913e/internal/provider/resource_gitlab_project_tag_test.go#L19

Comment (timofurrer) [reply internal/provider/resource_gitlab_group_test.go:205]: ... ah I see, then you are not able to easily attach it to that group under test 🤔

Comment (gro-gg) [reply internal/provider/resource_gitlab_group_test.go:216]: I've added a test, that ensures the group id does not change

**Comment by gro-gg** [comment]
done my work and rebased on master
ready for review :ping_pong:

**Review by timofurrer — APPROVED** [review]

**Review by timofurrer — APPROVED** [review]
Thanks for the contribution @gro-gg ! 🎉 

It looks good to me. 🚢 

Reminder for myself: we need to do something about the "testability" of these larger resources. The tests cases are somewhat a intransparent mix of feature testing ...
